/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author gusta
 */
public class FrmInserirValorEmCartao extends javax.swing.JFrame
{

    private int quantidadeAdicionada = 0;

    /**
     * Creates new form FrmInserirValorEmCartao
     */
    public FrmInserirValorEmCartao()
    {
        initComponents();
        verificarCbx();

    }

    private void alterarQuantidade(boolean quantidade)
    {
        if (quantidade)
        {
            quantidadeAdicionada++;            
            lblQuantidadeAdicionada.setText(Integer.toString(quantidadeAdicionada));
        } else
        {            
            if (quantidadeAdicionada > 0)
            {
                quantidadeAdicionada--;
                lblQuantidadeAdicionada.setText(Integer.toString(quantidadeAdicionada));
            }
            
        }
    }

    //Verifica se a caixa de seleção está com seu valor igual ao valor ou selo
    private void verificarCbx()
    {
        if (cbxTipoCartao.getSelectedItem() == "Valor")
        {
            lblQuantidade.setVisible(false);
            btnQuantidadeAumentar.setVisible(false);
            btnQuantidadeDiminuir.setVisible(false);
            txbValorCorte.setVisible(true);
            lblValorCorte.setVisible(true);
            lblQuantidadeAdicionada.setVisible(false);
        } else
        {
            lblQuantidade.setVisible(true);
            btnQuantidadeAumentar.setVisible(true);
            btnQuantidadeDiminuir.setVisible(true);
            txbValorCorte.setVisible(false);
            lblValorCorte.setVisible(false);
            lblQuantidadeAdicionada.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        txbValorCorte = new javax.swing.JTextField();
        cbxTipoCartao = new javax.swing.JComboBox<>();
        lblTipoCartao = new javax.swing.JLabel();
        lblValorCorte = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTotalResultado = new javax.swing.JLabel();
        btnQuantidadeAumentar = new javax.swing.JButton();
        btnQuantidadeDiminuir = new javax.swing.JButton();
        lblQuantidadeAdicionada = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txbValorCorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, -1));

        cbxTipoCartao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Valor", "Selo", " " }));
        cbxTipoCartao.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbxTipoCartaoActionPerformed(evt);
            }
        });
        jPanel1.add(cbxTipoCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, -1));

        lblTipoCartao.setText("Tipo de Cartão:");
        jPanel1.add(lblTipoCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        lblValorCorte.setText("Valor:");
        jPanel1.add(lblValorCorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lblQuantidade.setText("Quantidade:");
        jPanel1.add(lblQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lblTotal.setText("Total:");
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lblTotalResultado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTotalResultado.setText("0");
        jPanel1.add(lblTotalResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        btnQuantidadeAumentar.setText("+");
        btnQuantidadeAumentar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnQuantidadeAumentarActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuantidadeAumentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 40, -1));

        btnQuantidadeDiminuir.setText("-");
        btnQuantidadeDiminuir.setMaximumSize(new java.awt.Dimension(40, 25));
        btnQuantidadeDiminuir.setMinimumSize(new java.awt.Dimension(40, 25));
        btnQuantidadeDiminuir.setPreferredSize(new java.awt.Dimension(40, 25));
        btnQuantidadeDiminuir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnQuantidadeDiminuirActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuantidadeDiminuir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 40, -1));
        jPanel1.add(lblQuantidadeAdicionada, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jButton1.setText("Cancelar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        jButton2.setText("Cadastrar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTipoCartaoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbxTipoCartaoActionPerformed
    {//GEN-HEADEREND:event_cbxTipoCartaoActionPerformed
        verificarCbx();            // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoCartaoActionPerformed

    private void btnQuantidadeAumentarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnQuantidadeAumentarActionPerformed
    {//GEN-HEADEREND:event_btnQuantidadeAumentarActionPerformed
        alterarQuantidade(true);
    }//GEN-LAST:event_btnQuantidadeAumentarActionPerformed

    private void btnQuantidadeDiminuirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnQuantidadeDiminuirActionPerformed
    {//GEN-HEADEREND:event_btnQuantidadeDiminuirActionPerformed
        alterarQuantidade(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantidadeDiminuirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmInserirValorEmCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmInserirValorEmCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmInserirValorEmCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmInserirValorEmCartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FrmInserirValorEmCartao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuantidadeAumentar;
    private javax.swing.JButton btnQuantidadeDiminuir;
    private javax.swing.JComboBox<String> cbxTipoCartao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblQuantidadeAdicionada;
    private javax.swing.JLabel lblTipoCartao;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalResultado;
    private javax.swing.JLabel lblValorCorte;
    private javax.swing.JTextField txbValorCorte;
    // End of variables declaration//GEN-END:variables
}
