/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JInternalFrame;

/**
 *
 * @author gusta
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DpContainer = new javax.swing.JDesktopPane();
        MbMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MiCadastrarCliente = new javax.swing.JMenuItem();
        MiPesquisarClientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MiCadastrarFuncionario = new javax.swing.JMenuItem();
        MiPesquisarFuncionario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MiCadastrarEmpresa = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MiCadastrarCartao = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DpContainerLayout = new javax.swing.GroupLayout(DpContainer);
        DpContainer.setLayout(DpContainerLayout);
        DpContainerLayout.setHorizontalGroup(
            DpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        DpContainerLayout.setVerticalGroup(
            DpContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DpContainer)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DpContainer)
        );

        jMenu1.setText("Cliente");

        MiCadastrarCliente.setText("Cadastrar");
        MiCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiCadastrarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(MiCadastrarCliente);

        MiPesquisarClientes.setText("Pesquisar");
        MiPesquisarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiPesquisarClientesActionPerformed(evt);
            }
        });
        jMenu1.add(MiPesquisarClientes);

        MbMenu.add(jMenu1);

        jMenu2.setText("Funcionario");

        MiCadastrarFuncionario.setText("Cadastrar");
        MiCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiCadastrarFuncionarioActionPerformed(evt);
            }
        });
        jMenu2.add(MiCadastrarFuncionario);

        MiPesquisarFuncionario.setText("Pesquisar");
        MiPesquisarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiPesquisarFuncionarioActionPerformed(evt);
            }
        });
        jMenu2.add(MiPesquisarFuncionario);

        MbMenu.add(jMenu2);

        jMenu3.setText("Empresa");

        MiCadastrarEmpresa.setText("Cadastrar");
        MiCadastrarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiCadastrarEmpresaActionPerformed(evt);
            }
        });
        jMenu3.add(MiCadastrarEmpresa);

        jMenuItem6.setText("Pesquisar");
        jMenu3.add(jMenuItem6);

        MbMenu.add(jMenu3);

        jMenu4.setText("Cartão");

        MiCadastrarCartao.setText("Cadastrar");
        MiCadastrarCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiCadastrarCartaoActionPerformed(evt);
            }
        });
        jMenu4.add(MiCadastrarCartao);

        jMenuItem8.setText("Pesquisar");
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("Pesquisar Pontos");
        jMenu4.add(jMenuItem9);

        MbMenu.add(jMenu4);

        setJMenuBar(MbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MiCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiCadastrarClienteActionPerformed
        IFrmCadastroCliente frmCadastrarCliente = new IFrmCadastroCliente();
        DpContainer.add(frmCadastrarCliente);
        frmCadastrarCliente.setVisible(true);
        frmCadastrarCliente.setPosicao();
    }//GEN-LAST:event_MiCadastrarClienteActionPerformed

    private void MiCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiCadastrarFuncionarioActionPerformed
        IFrmCadastroFuncionario frmCadastroFuncionario = new IFrmCadastroFuncionario();
        DpContainer.add(frmCadastroFuncionario);
        frmCadastroFuncionario.setVisible(true);
        frmCadastroFuncionario.setPosicao();
    }//GEN-LAST:event_MiCadastrarFuncionarioActionPerformed

    private void MiCadastrarCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiCadastrarCartaoActionPerformed
        IFrmCadastrarCartao frmCadastrarCartao = new IFrmCadastrarCartao();
        DpContainer.add(frmCadastrarCartao);
        frmCadastrarCartao.setVisible(true);
        frmCadastrarCartao.setPosicao();

    }//GEN-LAST:event_MiCadastrarCartaoActionPerformed

    private void MiCadastrarEmpresaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MiCadastrarEmpresaActionPerformed
    {//GEN-HEADEREND:event_MiCadastrarEmpresaActionPerformed
        IFrmGestaoEmpresa frmCadastroEmpresa = new IFrmGestaoEmpresa();
        DpContainer.add(frmCadastroEmpresa);
        frmCadastroEmpresa.setVisible(true);
        frmCadastroEmpresa.setPosicao();
    }//GEN-LAST:event_MiCadastrarEmpresaActionPerformed

    private void MiPesquisarClientesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MiPesquisarClientesActionPerformed
    {//GEN-HEADEREND:event_MiPesquisarClientesActionPerformed
        IFrmPesquisarClientes frmPesquisarClientes = new IFrmPesquisarClientes();
        DpContainer.add(frmPesquisarClientes);
        frmPesquisarClientes.setVisible(true);
        frmPesquisarClientes.setPosicao();
    }//GEN-LAST:event_MiPesquisarClientesActionPerformed

    private void MiPesquisarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiPesquisarFuncionarioActionPerformed
        IFrmPesquisarFuncionarios iFrmPesquisarFuncionarios = new IFrmPesquisarFuncionarios();
        DpContainer.add(iFrmPesquisarFuncionarios);
        iFrmPesquisarFuncionarios.setVisible(true);
        iFrmPesquisarFuncionarios.setPosicao();
    }//GEN-LAST:event_MiPesquisarFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DpContainer;
    private javax.swing.JMenuBar MbMenu;
    private javax.swing.JMenuItem MiCadastrarCartao;
    private javax.swing.JMenuItem MiCadastrarCliente;
    private javax.swing.JMenuItem MiCadastrarEmpresa;
    private javax.swing.JMenuItem MiCadastrarFuncionario;
    private javax.swing.JMenuItem MiPesquisarClientes;
    private javax.swing.JMenuItem MiPesquisarFuncionario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
