/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.FuncionarioControl;
import Model.bean.EmpresaBEAN;
import Model.bean.FuncionarioBEAN;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author gusta
 */
public class IFrmCadastroFuncionario extends javax.swing.JInternalFrame
{

    private EnumCRUD crud;
    private FuncionarioBEAN funcionario;
    private IFrmPesquisarFuncionarios frmPesquisar;

    public IFrmCadastroFuncionario()
    {
        initComponents();
    }

    public IFrmCadastroFuncionario(EnumCRUD crud)
    {
        this();
        this.crud = crud;        
    }    
    public IFrmCadastroFuncionario(EnumCRUD crud,FuncionarioBEAN funcionario,IFrmPesquisarFuncionarios frmPesquisarFuncionarios)
    {        
        this(crud);
        this.funcionario = funcionario;
        frmPesquisar = frmPesquisarFuncionarios;
        if (crud == EnumCRUD.Cadastrar)
        {
            btnCadastroFuncionario.setText("Cadastrar");
        } else
        {
            
            btnCadastroFuncionario.setText("Alterar");
            txbNomeCompleto.setText(funcionario.getNome());
            txbLogin.setText(funcionario.getLogin());
            txbSenha.setText(funcionario.getSenha());
        }
        
        
    }    

    public void setPosicao()
    {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txbNomeCompleto = new javax.swing.JTextField();
        btnCadastroFuncionario = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txbLogin = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txbSenha = new javax.swing.JPasswordField();

        setClosable(true);
        setTitle("Cadastrar Funcionário");

        jLabel1.setText("Nome Completo:");

        btnCadastroFuncionario.setText("Cadastrar");
        btnCadastroFuncionario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCadastroFuncionarioActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        lblLogin.setText("Login");

        lblSenha.setText("Senha");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txbSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                        .addGap(235, 235, 235))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSenha)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(txbNomeCompleto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addComponent(lblLogin)
                                .addComponent(txbLogin)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastroFuncionario)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txbNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastroFuncionario)
                    .addComponent(btnCancelar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarActionPerformed
    {//GEN-HEADEREND:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCadastroFuncionarioActionPerformed
    {//GEN-HEADEREND:event_btnCadastroFuncionarioActionPerformed
        EmpresaBEAN empresaBEAN = new EmpresaBEAN();
        empresaBEAN.setIdEmpresa(1);
        FuncionarioBEAN funcionarioBEAN = new FuncionarioBEAN(txbNomeCompleto.getText(), empresaBEAN, txbLogin.getText(), txbSenha.getText());
        FuncionarioControl funcionarioControl = new FuncionarioControl();

        if (crud == EnumCRUD.Cadastrar)
        {

            if (funcionarioControl.inserirFuncionario(funcionarioBEAN))
            {
                JOptionPane.showMessageDialog(this, "Funcionario cadastrado com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                frmPesquisar.atualizarTable();                
            } else
            {
                JOptionPane.showMessageDialog(this, "Não foi possível cadastrar funcionário", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }else
        {
            funcionarioBEAN.setIdFuncionario(funcionario.getIdFuncionario());
            if (funcionarioControl.alterarFuncionario(funcionarioBEAN))
            {
                JOptionPane.showMessageDialog(this, "Funcionario alterado com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                frmPesquisar.atualizarTable();
                this.dispose();
            }
            else
            {
                 JOptionPane.showMessageDialog(this, "Não foi possivel alterar funcionario", "Erro", JOptionPane.ERROR_MESSAGE);
            }

            
            
        }
    }//GEN-LAST:event_btnCadastroFuncionarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroFuncionario;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txbLogin;
    private javax.swing.JTextField txbNomeCompleto;
    private javax.swing.JPasswordField txbSenha;
    // End of variables declaration//GEN-END:variables

}
